import { Deposit, Investment, Referral, ReferralBonus } from "./TableCol";

export const tradesData = [
  {
    id: 1,
    tradeType: "sell",
    tradeOption: "CRYPTO",
    pairs: "BTC/USDT",
    entry: "100$",
    lotSize: "1.0",
    takeProfit: 1.1934,
    stopLoss: 0.9065,
    profit: 0,
    status: "pending",
  },
  {
    id: 2,
    tradeType: "sell",
    tradeOption: "CRYPTO",
    pairs: "PEPE/USDT",
    entry: "100$",
    lotSize: "1.0",
    takeProfit: 1.1934,
    stopLoss: 0.9065,
    profit: 0,
    status: "success",
  },
  {
    id: 3,
    tradeType: "Buy",
    tradeOption: "CRYPTO",
    pairs: "BTC/SOL",
    entry: "100$",
    lotSize: "1.0",
    takeProfit: 1.1934,
    stopLoss: 0.9065,
    profit: 0,
    status: "success",
  },
];

export const forexPairs = [
  "AUD/CAD",
  "AUD/CHF",
  "AUD/JPY",
  "AUD/NZD",
  "AUD/USD",
  "EUR/AUD",
  "GBP/AUD",
  "AUD/CAD",
  "CAD/CHF",
  "CAD/JPY",
  "EUR/CAD",
  "GBP/CAD",
  "NZD/CAD",
  "USD/CAD",
  "AUD/CHF",
  "CAD/CHF",
  "CHF/JPY",
  "EUR/CHF",
  "GBP/CHF",
  "NZD/CHF",
  "USD/CHF",
  "EUR/AUD",
  "EUR/CAD",
  "EUR/CHF",
  "EUR/GBP",
  "EUR/JPY",
  "EUR/NZD",
  "EUR/USD",
  "GBP/AUD",
  "GBP/CAD",
  "GBP/CHF",
  "GBP/JPY",
  "GBP/NZD",
  "GBP/USD",
  "EUR/GBP",
  "NZD/CAD",
  "NZD/CHF",
  "NZD/JPY",
  "NDZ/USD",
  "AUD/NZD",
  "EUR/NZD",
  "AUD/JPY",
  "CAD/JPY",
  "CHF/JPY",
  "EUR/JPY",
  "GBP/JPY",
  "NZD/JPY",
  "USD/JPY",
  "AUD/USD",
  "EUR/USD",
  "GBP/USD",
  "NZD/USD",
  "USD/CAD",
  "USD/CHF",
  "USD/JPY",
];

export const cryptoPairs = [
  "ETH/USD",
  "BTC/USD",
  "ETH/USDT",
  "BTC/USDT",
  "USD/BTC",
  "USD/ETH",
  "USD/USDT",
  "USD/MATIC",
  "USD/ADA",
  "DAI/ETH",
  "DAI/USDC",
  "USDT/BTC",
  "USDT/ETH",
  "USDT/DOGE",
  "USDT/BCH",
  "USDT/LTC",
  "ETH/BTC",
  "ETH/BCH",
  "ETH/LINK",
  "ETH/ADA",
  "ETH/DOGE",
  "BTC/ETH",
  "BTC/DOGE",
  "BTC/LTC",
  "BTC/ADA",
  "BTC/XLM",
  "DAI/wETH",
];

export const usersData = [
  {
    withdrawals: [
      {
        amount: "500",
        date: "Sat Dec 30 2023",
        method: "Bitcoin",
        status: "Completed",
      },
      {
        amount: "500",
        date: "Sat Dec 30 2023",
        method: "Bitcoin",
        status: "Completed",
      },
      {
        amount: "500",
        date: "Sat Dec 30 2023",
        method: "Bitcoin",
        status: "Completed",
      },
      {
        amount: "500",
        date: "Sat Dec 30 2023",
        method: "Bitcoin",
        status: "Completed",
      },
    ],
    tradingSession: [
      {
        entry: "300",
        lotSize: "5LS",
        pairs: "USD/BTC",
        profit: "0",
        status: "pending",
        stopLoss: "2",
        takeProfit: "1",
        tradeOption: "BUY",
        tradeType: "CRYPTO",
        result: "Pending",
        date: new Date().toDateString(),
      },
      {
        entry: "500",
        lotSize: "2LS",
        pairs: "EUR/AUD",
        profit: "0",
        status: "pending",
        stopLoss: "1.0013",
        takeProfit: "1.100",
        tradeOption: "SELL",
        tradeType: "FOREX",
        result: "Pending",
        date: new Date().toDateString(),
      },
    ],
    depositHistory: [
      {
        amount: 2000,
        date: "Sat Dec 30 2023",
        method: "Bitcoin",
        status: "pending",
        totalBalance: "0.000",
        totalBonus: "0.000",
        totalProfit: "0.000",
      },
    ],
    user: {
      country: "Australia",
      email: "kelsmith@gmail.com",
      firstname: "Kel",
      lastname: "Smith",
      username: "Kels",
      gender: "male",
      mobile: "23399945589",
      password: process.env.REACT_APP_PASSWORD,
      status: "active",
      joinedDate: new Date().toDateString(),
    },
    subscription: {
      plan: "SILVER",
      amount: "10000",
      duration: "7days",
      date: new Date().toDateString(),
    },
    verification: {
      document: "document",
      status: "Pending",
    },
    totalBalance: "0.000",
    totalProfit: "0.000",
    totalBonus: "0.000",
  },
  {
    widthdrawal: [
      {
        amount: "500",
        date: "Sat Dec 30 2023",
        method: "Bitcoin",
        status: "pending",
      },
    ],
    tradingSession: [
      {
        entry: "300",
        lotSize: "5LS",
        pairs: "USD/BTC",
        profit: "0",
        status: "pending",
        stopLoss: "1.0013",
        takeProfit: "1.100",
        tradeOption: "BUY",
        tradeType: "CRYPTO",
        result: "Pending",
        date: new Date().toDateString(),
      },
      {
        entry: "500",
        lotSize: "2LS",
        pairs: "EUR/AUD",
        profit: "0",
        status: "Completed",
        stopLoss: "1.0013",
        takeProfit: "1.100",
        tradeOption: "SELL",
        tradeType: "FOREX",
        result: "Win",
        date: new Date().toDateString(),
      },
    ],
    depositHistory: [
      {
        amount: 2000,
        date: "Sat Dec 30 2023",
        method: "Bitcoin",
        status: "Completed",
      },
    ],
    user: {
      country: "Australia",
      email: "franklinsmith@gmail.com",
      firstname: "Franklin",
      lastname: "Smith",
      username: "Franklin",
      gender: "Male",
      mobile: "23399945589",
      password: process.env.REACT_APP_PASSWORD,
      status: "active",
      joinedDate: new Date().toDateString(),
    },
    subscription: {
      plan: "SILVER",
      amount: "10000",
      duration: "7days",
      date: new Date().toDateString(),
    },
    verification: {
      document: "document",
      status: "Verified",
    },
    totalBalance: "0.000",
    totalProfit: "0.000",
    totalBonus: "0.000",
  },
];

export const depositData = [
  {
    method: "Bitcoin Address",
    amount: 199,
    status: "Completed",
    date: "Mon, 18-Dec-2023",
  },
];

export const withdrawalData = [
  {
    method: "Bitcoin Address",
    amount: "200",
    status: "Completed",
    date: "Mon, 18-Dec-2023",
  },
  {
    method: "Bitcoin Address",
    amount: "200",
    status: "Completed",
    date: "Mon, 18-Dec-2023",
  },
  {
    method: "Bitcoin Address",
    amount: "199",
    status: "Completed",
    date: "Mon, 18-Dec-2023",
  },
  {
    method: "Bitcoin Address",
    amount: "500",
    status: "Completed",
    date: "Mon, 18-Dec-2023",
  },
];

export const usersInfo = [
  {
    userId: "1",
    firstname: "John",
    lastname: "Doe",
    username: "jonnycrane",
    mobile: "08162435269",
    password: "gweygyweg",
    country: "Nigeria",
    status: "Active",
    joinedDate: "30th Apr, 2024",
    gender: "male",
    email: "john@gmail.com",
    totalBalance: "100",
    totalProfit: "400",
    totalBonus: "350",
  },
  {
    userId: "2",
    firstname: "Johndef",
    lastname: "Doeeey",
    username: "jonnycranexvr",
    mobile: "08162435269",
    password: "gsdygygdsy",
    country: "Nigeria",
    status: "Active",
    joinedDate: "30th Apr, 2024",
    gender: "male",
    email: "johndef@gmail.com",
    totalBalance: "1000",
    totalProfit: "4,500",
    totalBonus: "350",
  },
  {
    userId: "3",
    firstname: "mary",
    lastname: "jane",
    username: "mj235",
    mobile: "08162435269",
    password: "sgdgygsdy",
    country: "Nigeria",
    status: "upgrade",
    joinedDate: "30th Apr, 2024",
    gender: "male",
    email: "mary@gmail.com",
    totalBalance: "1000",
    totalProfit: "4,500",
    totalBonus: "350",
  },
  {
    userId: "1",
    firstname: "John",
    lastname: "Doe",
    username: "jonnycrane",
    mobile: "08162435269",
    password: "ttftf",
    country: "Nigeria",
    status: "Active",
    joinedDate: "30th Apr, 2024",
    gender: "male",
    email: "john@gmail.com",
    totalBalance: "100",
    totalProfit: "400",
    totalBonus: "350",
  },
  {
    userId: "2",
    firstname: "Johndef",
    lastname: "Doeeey",
    username: "jonnycranexvr",
    mobile: "08162435269",
    password: "sdgygydsg",
    country: "Nigeria",
    status: "Active",
    joinedDate: "30th Apr, 2024",
    gender: "male",
    email: "johndef@gmail.com",
    totalBalance: "1000",
    totalProfit: "4,500",
    totalBonus: "350",
  },
  {
    userId: "3",
    firstname: "mary",
    lastname: "jane",
    username: "mj235",
    mobile: "08162435269",
    password: "svsdsdggsd",
    country: "Nigeria",
    status: "upgrade",
    joinedDate: "30th Apr, 2024",
    gender: "male",
    email: "mary@gmail.com",
    totalBalance: "1000",
    totalProfit: "4,500",
    totalBonus: "350",
  },
  {
    userId: "4",
    firstname: "mary",
    lastname: "jane",
    username: "mj235",
    mobile: "08162435269",
    password: "svsdsdggsd",
    country: "Nigeria",
    status: "upgrade",
    joinedDate: "30th Apr, 2024",
    gender: "male",
    email: "mary@gmail.com",
    totalBalance: "1000",
    totalProfit: "4,500",
    totalBonus: "350",
  },
  {
    userId: "5",
    firstname: "mary",
    lastname: "jane",
    username: "mj235",
    mobile: "08162435269",
    password: "svsdsdggsd",
    country: "Nigeria",
    status: "upgrade",
    joinedDate: "30th Apr, 2024",
    gender: "male",
    email: "mary@gmail.com",
    totalBalance: "1000",
    totalProfit: "4,500",
    totalBonus: "350",
  },
  {
    userId: "6",
    firstname: "mary",
    lastname: "jane",
    username: "mj235",
    mobile: "08162435269",
    password: "svsdsdggsd",
    country: "Nigeria",
    status: "upgrade",
    joinedDate: "30th Apr, 2024",
    gender: "male",
    email: "mary@gmail.com",
    totalBalance: "1000",
    totalProfit: "4,500",
    totalBonus: "350",
  },
  {
    userId: "7",
    firstname: "mary",
    lastname: "jane",
    username: "mj235",
    mobile: "08162435269",
    password: "svsdsdggsd",
    country: "Nigeria",
    status: "upgrade",
    joinedDate: "30th Apr, 2024",
    gender: "male",
    email: "mary@gmail.com",
    totalBalance: "1000",
    totalProfit: "4,500",
    totalBonus: "350",
  },
];

export const history: any = [
  {
    userId: "1",
    date: "30th Apr, 2024",
    method: "Bitcoin Address",
    status: "Completed",
    fullname: "John Doe",
    id: "1",
    screenshot:
      "https://plus.unsplash.com/premium_photo-1681400690940-8eff232a8f7d?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OXx8Y3B1JTIwY2hpcHxlbnwwfHwwfHx8MA%3D%3D",
    amount: "1500",
    tradeType: "Forex",
    tradeOption: "Sell",
    pairs: "AUD/USD",
    lotSize: "3",
    entry: "500",
    stopLoss: "1",
    takeProfit: "1.001",
    profit: "600",
  },
  {
    userId: "1",
    date: "20th Apr, 2024",
    method: "Bitcoin Address",
    status: "Pending",
    fullname: "Johnyy Doese",
    id: "2",
    screenshot:
      "https://plus.unsplash.com/premium_photo-1681400690940-8eff232a8f7d?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OXx8Y3B1JTIwY2hpcHxlbnwwfHwwfHx8MA%3D%3D",
    amount: "1500",
    tradeType: "Crypto",
    tradeOption: "Buy",
    pairs: "PEPE/USDT",
    lotSize: "10",
    entry: "400",
    stopLoss: "2",
    takeProfit: "2.05",
    profit: "3000",
  },
];

export const subscriptions = [
  {
    userId: "1",
    date: "20th Apr, 2024",
    plan: "Silver Plan",
    status: "Pending",
    fullname: "Johnyy Doese",
    id: "2",
    amount: "1,500",
    duration: "7days",
  },

  {
    userId: "2",
    date: "20th Apr, 2024",
    plan: "Silver Plan",
    status: "Pending",
    fullname: "Johnyy Doese",
    id: "2",
    amount: "1,500",
    duration: "7days",
  },
];

export const verifications = [
  {
    userId: "1",
    date: "20th Apr, 2024",
    document: "Silver Plan",
    status: "Pending",
    fullname: "Johnyy Doese",
    id: "2",
  },
  {
    userId: "2",
    date: "20th Apr, 2024",
    document: "Silver Plan",
    status: "Verified",
    fullname: "Johnyy Doese",
    id: "2",
  },
];

export const notifications = [
  {
    userId: "1",
    date: "20th Apr, 2024",
    noteTitle: "Deposit Bonus",
    status: "Inactive",
    fullname: "Johnyy Doese",
    id: "2",
    message: "Deposit through the deposit page to get a $500 bonus on your deposits through 12/25.",
  },
  {
    userId: "2",
    date: "20th Apr, 2024",
    noteTitle: "Withdrawal Bonus",
    status: "Active",
    fullname: "Lionel Messi",
    id: "2",
    message: "Withdraw through the withdrawal page to get a $500 bonus on your deposits through 12/25.",
  },
];

export const deposits: Deposit[] = [
  {
    transactionType: "Deposit",
    paymentMethod: "Credit Card",
    amount: "$1500.00",
    status: "success",
    time: "2024-08-29 12:34:56",
  },
  {
    transactionType: "Deposit",
    paymentMethod: "Bank Transfer",
    amount: "$3000.00",
    status: "pending",
    time: "2024-08-28 09:12:45",
  },
  {
    transactionType: "Deposit",
    paymentMethod: "PayPal",
    amount: "$750.00",
    status: "failed",
    time: "2024-08-27 16:23:10",
  },
  {
    transactionType: "Deposit",
    paymentMethod: "Crypto",
    amount: "$2000.00",
    status: "success",
    time: "2024-08-26 14:10:22",
  },
  {
    transactionType: "Deposit",
    paymentMethod: "Debit Card",
    amount: "$500.00",
    status: "success",
    time: "2024-08-25 10:45:33",
  },
  {
    transactionType: "Deposit",
    paymentMethod: "Credit Card",
    amount: "$1200.00",
    status: "pending",
    time: "2024-08-24 18:52:47",
  },
  {
    transactionType: "Deposit",
    paymentMethod: "Bank Transfer",
    amount: "$2500.00",
    status: "success",
    time: "2024-08-23 11:30:12",
  },
  {
    transactionType: "Deposit",
    paymentMethod: "PayPal",
    amount: "$1800.00",
    status: "failed",
    time: "2024-08-22 13:20:55",
  },
  {
    transactionType: "Deposit",
    paymentMethod: "Credit Card",
    amount: "$1500.00",
    status: "success",
    time: "2024-08-29 12:34:56",
  },
  {
    transactionType: "Deposit",
    paymentMethod: "Bank Transfer",
    amount: "$3000.00",
    status: "pending",
    time: "2024-08-28 09:12:45",
  },
  {
    transactionType: "Deposit",
    paymentMethod: "PayPal",
    amount: "$750.00",
    status: "failed",
    time: "2024-08-27 16:23:10",
  },
  {
    transactionType: "Deposit",
    paymentMethod: "Crypto",
    amount: "$2000.00",
    status: "success",
    time: "2024-08-26 14:10:22",
  },
];

export const investments: Investment[] = [
  {
    investmentOption: "High Yield Savings",
    capital: "$5000",
    profit: "$250",
    start: "2024-01-15",
    end: "2024-07-15",
    status: "completed",
  },
  {
    investmentOption: "Stocks",
    capital: "$2000",
    profit: "$100",
    start: "2024-03-01",
    end: "2024-09-01",
    status: "active",
  },
  {
    investmentOption: "Bonds",
    capital: "$3000",
    profit: "$150",
    start: "2024-02-20",
    end: "2024-08-20",
    status: "completed",
  },
  {
    investmentOption: "Real Estate",
    capital: "$10000",
    profit: "$500",
    start: "2024-05-10",
    end: "2024-11-10",
    status: "active",
  },
  {
    investmentOption: "Mutual Funds",
    capital: "$1500",
    profit: "$75",
    start: "2024-04-05",
    end: "2024-10-05",
    status: "completed",
  },
  {
    investmentOption: "Cryptocurrency",
    capital: "$2500",
    profit: "$300",
    start: "2024-06-15",
    end: "2024-12-15",
    status: "active",
  },
  {
    investmentOption: "Treasury Bills",
    capital: "$2000",
    profit: "$80",
    start: "2024-01-25",
    end: "2024-07-25",
    status: "completed",
  },
  {
    investmentOption: "Index Funds",
    capital: "$3500",
    profit: "$200",
    start: "2024-07-01",
    end: "2024-12-31",
    status: "active",
  },
  {
    investmentOption: "ETFs",
    capital: "$1800",
    profit: "$90",
    start: "2024-02-15",
    end: "2024-08-15",
    status: "completed",
  },
  {
    investmentOption: "Savings Account",
    capital: "$1200",
    profit: "$60",
    start: "2024-03-10",
    end: "2024-09-10",
    status: "completed",
  },
];

export const referrals: Referral[] = [
  {
    fullname: "Alice Johnson",
    email: "alice.johnson@example.com",
    date: "2024-08-01",
    status: "active",
  },
  {
    fullname: "Bob Smith",
    email: "bob.smith@example.com",
    date: "2024-08-02",
    status: "pending",
  },
  {
    fullname: "Charlie Brown",
    email: "charlie.brown@example.com",
    date: "2024-08-03",
    status: "active",
  },
  {
    fullname: "Dana White",
    email: "dana.white@example.com",
    date: "2024-08-04",
    status: "pending",
  },
  {
    fullname: "Eva Green",
    email: "eva.green@example.com",
    date: "2024-08-05",
    status: "active",
  },
  {
    fullname: "Frank Black",
    email: "frank.black@example.com",
    date: "2024-08-06",
    status: "pending",
  },
  {
    fullname: "Grace Lee",
    email: "grace.lee@example.com",
    date: "2024-08-07",
    status: "active",
  },
  {
    fullname: "Hank Davis",
    email: "hank.davis@example.com",
    date: "2024-08-08",
    status: "pending",
  },
  {
    fullname: "Ivy Clark",
    email: "ivy.clark@example.com",
    date: "2024-08-09",
    status: "active",
  },
  {
    fullname: "Jack Wilson",
    email: "jack.wilson@example.com",
    date: "2024-08-10",
    status: "pending",
  },
];

export const referralBonuses: ReferralBonus[] = [
  {
    referralName: "Alice Johnson",
    email: "alice.johnson@example.com",
    amount: "$50",
    date: "2024-08-02",
  },
  {
    referralName: "Bob Smith",
    email: "bob.smith@example.com",
    amount: "$25",
    date: "2024-08-03",
  },
  {
    referralName: "Charlie Brown",
    email: "charlie.brown@example.com",
    amount: "$75",
    date: "2024-08-04",
  },
  {
    referralName: "Dana White",
    email: "dana.white@example.com",
    amount: "$30",
    date: "2024-08-05",
  },
  {
    referralName: "Eva Green",
    email: "eva.green@example.com",
    amount: "$40",
    date: "2024-08-06",
  },
  {
    referralName: "Frank Black",
    email: "frank.black@example.com",
    amount: "$20",
    date: "2024-08-07",
  },
  {
    referralName: "Grace Lee",
    email: "grace.lee@example.com",
    amount: "$60",
    date: "2024-08-08",
  },
  {
    referralName: "Hank Davis",
    email: "hank.davis@example.com",
    amount: "$35",
    date: "2024-08-09",
  },
  {
    referralName: "Ivy Clark",
    email: "ivy.clark@example.com",
    amount: "$45",
    date: "2024-08-10",
  },
  {
    referralName: "Jack Wilson",
    email: "jack.wilson@example.com",
    amount: "$50",
    date: "2024-08-11",
  },
];
